name: Build and Deploy to AWS EC2

on:
  push:
    branches:
      - developer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Navigate to project directory
        run: cd ecuaplanet  
      - name: Build with Maven
        run: mvn clean install -DskipTests

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Save key and set permissions
        run: |
          echo "${{ secrets.EC2_KEY_PAIR }}" > ec2-key.pem
          chmod 400 ec2-key.pem

      - name: Deploy to EC2
        run: |
          scp -i ec2-key.pem target/*.jar ec2-user@<EC2_PUBLIC_IP>:/home/ec2-user/app.jar
          ssh -i ec2-key.pem ec2-user@<EC2_PUBLIC_IP> << 'EOF'
            sudo yum update -y
            sudo amazon-linux-extras enable corretto11
            sudo yum install java-11-amazon-corretto -y
            nohup java -jar /home/ec2-user/app.jar > app.log 2>&1 &
          EOF
