name: Build and Deploy to AWS EC2

on:
  push:
    branches:
      - developer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: spring-boot-app
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Cambia la región si es necesario

      - name: Deploy to EC2
        run: |
          scp -i ${{ secrets.EC2_KEY_PAIR }} target/*.jar ec2-user@<EC2_PUBLIC_IP>:/home/ec2-user/app.jar
          ssh -i ${{ secrets.EC2_KEY_PAIR }} ec2-user@<EC2_PUBLIC_IP> << 'EOF'
            java -jar /home/ec2-user/app.jar &
          EOF
