name: Build and Deploy to AWS EC2

on:
  push:
    branches:
      - developer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          cd ecuaplanet/
          mvn clean install -DskipTests
          ls -l target/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Save key and set permissions
        run: |
          echo "${{ secrets.EC2_KEY_PAIR }}" > Ecuaplanet.pem
          chmod 400 Ecuaplanet.pem

      - name: Deploy to EC2
        run: |
          scp -i Ecuaplanet.pem ecuaplanet/target/*.jar ec2-user@54.204.157.26:/home/ec2-user/app.jar
          ssh -i Ecuaplanet.pem ec2-user@54.204.157.26 << 'EOF'
            sudo yum update -y
            sudo amazon-linux-extras enable corretto11
            sudo yum install java-17-amazon-corretto -y
            nohup java -jar /home/ec2-user/app.jar > app.log 2>&1 &
          EOF
